version: "2"
services:

  # web:
  #   build:
  #     context: ./docker/web/
  #   environment:
  #      - PATH=/var/www/html/vendor/bin/:$PATH
  #      - TYPO3_CONTEXT=Development/Docker
  #   env_file:
  #     - etc/environment.yml
  #   ports:
  #     - "80:80"
  #   volumes:
  #       - ./app/web/:/var/www/html/
  #       - ./bin:/opt/docker/bin/
  #       - ./etc/apache2:/etc/apache2
  #       - ./etc/php:/usr/local/etc/php
  web:
    build:
      context: ./docker/nginx_fpm_tcp
    env_file:
      - etc/environment.yml
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   retries: 3
    command: >
      /bin/bash -c "envsubst '$$FQDN' <
      /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf
      && cat /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"

    volumes:
      - ./app/web:/var/www/html

  php_fpm:
    build:
      context: ./docker/fpm
    volumes_from:
      - web
    env_file:
      - etc/environment.yml

#   mariadb:
#     container_name: mariadb
#     image: mariadb
#     env_file:
#       - etc/environment.yml
#     volumes:
#      - mysql_data:/var/lib/mysql
#
#   composer:
#     container_name: composer
#     restart: 'no'
#     image: composer/composer:php7
#     working_dir: /var/www/html
#   #  command: install
#     depends_on:
#       - web
#       - mariadb
#     volumes_from:
#       - web
#   mail:
#     image: mailhog/mailhog
#     ports:
#       - 8025:8025
#
#   compass:
#     container_name: compass
#     build:
#       context: ./docker/compass
#     volumes_from:
#       - web
#     depends_on:
#       - web
#
# volumes:
#   mysql_data:
